set (SOURCES ${SOURCES}
		membrane_transport/nmodl_converter/converted/na_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/ca_converted_allNernst_UG.cpp 
		membrane_transport/nmodl_converter/converted/pump_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/caL3d_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/cad_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/ar_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/ca_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/kca_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/kir_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/km_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/inwardrect_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/CaT_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/kv_converted_standard_UG.cpp  
		membrane_transport/nmodl_converter/converted/HH2_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/h_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/hh_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/NMDA_Mg_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/NMDA_Mg_T_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/passive_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/release_BMK_converted_standard_UG.cpp 
		membrane_transport/nmodl_converter/converted/release_exp_converted_standard_UG.cpp
		membrane_transport/nmodl_converter/converted/Kv4_csi_converted_standard_UG.cpp
		membrane_transport/nmodl_converter/converted/Kv4_csiosi_converted_standard_UG.cpp
		membrane_transport/nmodl_converter/converted/myseclamp_converted_standard_UG.cpp
	)